spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
      platform: h2
      mode: ALWAYS
      continue-on-error: false
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #url: jdbc:h2:mem:dbtest;DATABASE_TO_UPPER=false;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    url: 'jdbc:h2:file:${H2_FILE_PATH:~/pomUpdateDb};DATABASE_TO_UPPER=false;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;'
    username: ${H2_USERNAME:pomUpdate}
    password: ${H2_PWD:pomUpdate}
    driver-class-name: org.h2.Driver

  jpa:
    #开发时打开sql显示
    show-sql: true