spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
#      platform: h2
      # ALWAYS /
      mode: ${DB_INIT:NEVER}
      continue-on-error: false
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: 'jdbc:mysql://${MYSQL_ADDR:localhost:3306}/db_pom_update?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&rewriteBatchStatements=true&allowPublicKeyRetrieval=true'
      username: ${MYSQL_USER:pom_update}
      password: ${MYSQL_PWD:pompompom}
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # durid web 依赖 javax
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          # 开发可以打开，但有一定性能损耗
          log-slow-sql: false
          slow-sql-millis: 5000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

    #日志配置
logging:
  logback:
    rollingpolicy:
      max-file-size: 20MB
      total-size-cap: 10000000
      max-history: 10

  file:
    max-history: 10
    max-size: 20MB
    path: /applications/pom-update/logs